# Generated by Django 4.1.7 on 2023-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.TimeField()),
                ('current_data', models.DateField()),
                ('bus_station', models.CharField(max_length=60)),
                ('route_number', models.IntegerField()),
            ],
        ),
    ]
